version: '3.3'

volumes:
  mongodb_data:
  mysql_data:

services:
  mongo:
    image: mongo:5.0.0-focal
    volumes:
      - 'mongodb_data:/Users/Shared/mongodb'
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=deng
    volumes:
      - 'mysql_data:/Users/Shared/mysql'
    ports:
      - "3306:3306"
